name: CI

on:
  push:
    branches:
    - master

jobs:
  main_job:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Add CNAME File
      run: | 
        cd ./dist
        echo "admin-demo.eviler.top" > CNAME
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: dist